source("~/Geyser/R/event_detector.r")
source("~/Geyser/R/timestamp_diff.r")
source("~/Geyser/R/metrics.r")

source("~/Geyser/R/Merge/import_merge.r")
source("~/Geyser/R/Compare/setup.r")
source("~/Geyser/R/Compare/prepare.r")
source("~/Geyser/R/Compare/analyze_compare.r")
source("~/Geyser/R/Compare/metrics_compare.r")
source("~/Geyser/R/Compare/plot_compare.r")
